CREATE DATABASE IF NOT EXISTS yeticave
    DEFAULT CHARACTER SET utf8
    DEFAULT COLLATE utf8_general_ci;

USE yeticave;

CREATE TABLE IF NOT EXISTS outfit_categories (
    id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS users (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    reg_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    email VARCHAR(50) NOT NULL UNIQUE,
    login VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(32) NOT NULL,
    contacts VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS users_lots (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    reg_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    outfit_title VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    img_url VARCHAR(255) NOT NULL UNIQUE,
    starting_price MEDIUMINT UNSIGNED NOT NULL,
    expiry_date TIMESTAMP NOT NULL,
    bid_step SMALLINT UNSIGNED NOT NULL,
    user_id INT UNSIGNED NOT NULL,
    winner_id INT UNSIGNED NULL,
    outfit_category_id TINYINT UNSIGNED NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (winner_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (outfit_category_id) REFERENCES outfit_categories (id)ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS lots_bids (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    reg_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    bid_amount MEDIUMINT UNSIGNED NOT NULL,
    user_id INT UNSIGNED NOT NULL,
    lot_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (lot_id)  REFERENCES users_lots(id) ON UPDATE CASCADE ON DELETE CASCADE
);


